# Generated by Django 5.2.8 on 2025-11-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='id',
        ),
        migrations.RemoveField(
            model_name='light',
            name='is_on',
        ),
        migrations.AlterField(
            model_name='light',
            name='light_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
